### ISSUE TITLE
Optie amount niet als een integer in centen

### ISSUE THREAD

**Issue by BondITSolutions** [paynl/sdk#1]
Waarom verwacht de SDK een bedrag als een float (e.g. 10.00) i.p.v. gewoon het bedrag in centen als een integer (e.g. 1000)?
https://github.com/paynl/sdk/blob/master/src/Transaction.php#L38

De API verwacht wel gewoon een integer in centen. Het staat ook nergens in de documentatie aangegeven dat de SDK geen bedrag in centen verwachten.

**Comment by andypieters** [comment]
In de SDK heb ik geprobeerd de minder logische dingen in de API weg te werken.
Een bedrag meegeven in centen is iets dat je eigenlijk alleen in onze api ziet.
Bij bijvoorbeeld paypal is dit niet het geval.

Daarom heb ik er voor gekozen om in de SDK met de bedragen te werken in euro.

Hetzelfde geldt voor de productregels.

**Comment by BondITSolutions** [comment]
Helemaal duidelijk, thanks.
