### ISSUE TITLE
PSR-4 compatible

### ISSUE THREAD

**Issue by marcolemmens-sw** [paynl/sdk#118]
`Deprecation Notice: Class Paynl\Result\Transaction\transactionDetails located in ./vendor/paynl/sdk/src/Result/Transaction/TransactionDetails.php does not comply with psr-4 autoloading standard. It will not autoload anymore in Composer v2.0. in /usr/share/php/Composer/Autoload/ClassMapGenerator.php:201`

Renaming the classname from transactionDetails to TransactionDetails should fix the problem and makes the whole PSR-4 compatible.

**Comment by woutse** [comment]
Thanks for letting us know! We will fix this asap.
