### ISSUE TITLE
Add option for CURLOPT_CAINFO

### ISSUE THREAD

**Issue by LorenzV** [paynl/sdk#12]
Please add the option to set a certificate file for the curl request.

I have 2 options at this moment, but they are both bad practice:
- Configure curl.cainfo file in php.ini
- Edit the composer package

Without this any curl request to https:// fails. (And i won't disable "SSL_VERIFYPEER")

**Comment by andypieters** [comment]
Good point,
Ill add it tomorrow

Op woensdag 17 februari 2016 heeft Lorenz Vandevelde <
notifications@github.com> het volgende geschreven:

**Comment by andypieters** [comment]
Added it in version 1.1.7

use \Paynl\Config::setCAInfoLocation('/path/to/the/file'); to set the location of the file

**Comment by LorenzV** [comment]
Amazing :+1: 
Thank you!
