### ISSUE TITLE
Exception when trying to print/send invoices manually

### ISSUE THREAD

**Issue by Kees-kees** [paynl/sdk#125]
After placing an order, and trying to generate/send an invoice manually, Magento returns the following mention on the screen: "`The invoice can't be saved at this time. Please try again later.`"

When looking at the exceptions log of Magento, the following shows up: "`main.CRITICAL: 'TransactionId is niet geset' is required {"exception":"[object] (Paynl\\Error\\Required(code: 0): 'TransactionId is niet geset' is required at /vendor/paynl/sdk/src/Api/Transaction/Capture.php:68)"} []`"

Any ideas why this is happening and how this can be fixed?

**Comment by woutse** [comment]
Thanks for your message! Could you please e-mail this to support@pay.nl? We'll investigate and come back to you asap!
