### ISSUE TITLE
Confusing result for transaction refund

### ISSUE THREAD

**Issue by czim** [paynl/sdk#133]
The documentation and SDK logic of the handling of refunds is confusing.

1.
In the [Refund result class](https://github.com/paynl/sdk/blob/master/src/Result/Transaction/Refund.php), references are made, in methods like [Refund::getRefundAmount](https://github.com/paynl/sdk/blob/8047d444f9959d6cad48d893f2c1406c27292cf8/src/Result/Transaction/Refund.php#L56), to method [Refund::getRefundedTransaction](https://github.com/paynl/sdk/blob/8047d444f9959d6cad48d893f2c1406c27292cf8/src/Result/Transaction/Refund.php#L26) that use it like an array, while the docblock indicates that it is a string. Is it an array?

2.
In the documentation, there is no specific `Transaction::Refund` documentation page for the API, so I would expect the request & response for refunds on this page to describe what's going on:
https://docs.pay.nl/developers#refunds

However, this does not include the fields that the SDK refers to; the SDK does seem to simply take the response content as is and feed it directly into the result class mentioned under point 1. Which is correct? The SDK or the documentation? Or am I missing something?

**Comment by escruickshank** [comment]
Hi! This issue is still unanswered! Sorry for that.
Yes, method refund:getRefundAmount returns a string, based on the getRefundedTransaction.
The documentation on docs.pay is about the core Pay. API, not this SDK.
