### ISSUE TITLE
An error is returned when getList is called

### ISSUE THREAD

**Issue by garygwl** [paynl/sdk#156]
When I try to use the example in the SDK, I get an error.

`\Paynl\Config::setTokenCode('AT-####-####');`
`\Paynl\Config::setApiToken('****************************************');`
`\Paynl\Config::setServiceId('SL-####-####');`
`$paymentMethods = \Paynl\Paymentmethods::getList();`
`var_dump($paymentMethods);`

return error：
`HTTP/1.1 422 Unprocessable Entity`

Please look at this for me. Thank you very much!

**Comment by woutse** [comment]
Please send an email to support@pay.nl to check your credentials. Above script should work.
