### ISSUE TITLE
Documentation about `statsdata.object` confusing

### ISSUE THREAD

**Issue by remcotolsma** [paynl/sdk#157]
As a partner of Pay.nl, we have received a request to add `statsdata.object` to the [Pronamic Pay plugin](https://www.pronamicpay.com/nl/) so that Pay.nl can measure the number of transactions that are initiated via our plugin. What we noticed was that the documentation on this is somewhat confusing. We just had your partner manager Fréderique and a colleague visiting. They indicated that the documentation is very good. In this issue a number of things that we found confusing.

https://docs.pay.nl/developers#mandatory-data-technical-partners

<img width="1030" alt="Scherm­afbeelding 2022-12-01 om 14 56 51" src="https://user-images.githubusercontent.com/869674/205071340-99edb171-18e5-4d2d-81f8-ca951d79a514.png">

The parameters is named `object` but is of the type `string`, why do you use the name `object` for this? For us it's confusing since `object` is also a (PHP) type.

---

On the `Transaction:START` documentation page: https://docs.pay.nl/developers#transaction-paylater this `object` parameter is not documented?

<img width="1011" alt="Scherm­afbeelding 2022-12-01 om 14 59 55" src="https://user-images.githubusercontent.com/869674/205071945-6997ec18-8f65-426e-8f3b-274320c298f0.png">

On this page you also mention `statsData` (camelCase) instead of `statsdata`. Are these the same parameters or are they different things?

---

Many of the `statsData` parameters are quite unclear to us, where do you use these parameters for?

- `promotorId`
- `info`
- `tool`
- `transferData`

---

In addition to https://docs.pay.nl/developers#transaction-paylater, we discovered https://developer.pay.nl/reference/post_transactions today via https://www.pay.nl/en/. There is an API https://rest.pay.nl/v1/ and an API https://rest-api.pay.nl/v16/? What is the story behind that and what should we use now?

---

On https://docs.pay.nl/developers?language=nl we also read the following:

> Bij elk API verzoek dien je de versie van de functie aan te geven. Welke versies per functie beschikbaar zijn vind je in de [API documentatie](https://admin.pay.nl/docpanel/api).

<img width="1027" alt="Scherm­afbeelding 2022-12-01 om 15 15 48" src="https://user-images.githubusercontent.com/869674/205075555-a6147421-1bbf-4bcb-b522-f2ae6d09c6ea.png">

We don't see this in the documentation? We were still using version `v4`, but it is very difficult to see what has changed since then?

---

On https://developer.pay.nl/docs/glossary-1#stats-parameters we see the following:

<img width="838" alt="Scherm­afbeelding 2022-12-01 om 15 18 26" src="https://user-images.githubusercontent.com/869674/205076076-7acd3151-0019-4645-8c78-7bb8621e3508.png">

On https://developer.pay.nl/reference/post_transactions we see:

<img width="635" alt="Scherm­afbeelding 2022-12-01 om 15 19 23" src="https://user-images.githubusercontent.com/869674/205076361-38f23d6d-eb72-4040-b920-0524f9392dd0.png">

Is the maximum length now `32` or `64` characters?

**Comment by escruickshank** [comment]
Hi! Thank you for being a partner of Pay.
Those are quite a few questions! It might be easier to answer these via an eMeeting. Please can you book some time with me via this link https://www.pay.nl/meetings/ellen-cruickshank I will be happy to talk you through our system.

**Comment by remcotolsma** [comment]
That is not necessary, we understand from your colleague Fréderique or another colleague that you are proud of your documentation. Perhaps you can improve the documentation based on these questions? I assume that's why you asked to share our feedback?

**Comment by escruickshank** [comment]
Hi! We have processed the feedback where relevant. Thank you for your input.

**Comment by remcotolsma** [comment]
Can you elaborate a bit on how the feedback was processed? We can't see improvements / changes in the documentation yet? There's no rush, but it would be nice if our questions were answered in the documentation. We regularly consult the documentation when writing code and solving problems.

**Comment by escruickshank** [comment]
Hi! We have adjusted the statsdata to statsData on https://docs.pay.nl/developers#mandatory-data-technical-partners and we have clarified the correct character limit (64) on https://developer.pay.nl/docs/glossary-1#stats-parameters.

**Comment by remcotolsma** [comment]
Thanks for that. This still leaves a number of questions unanswered. Do the open questions still have your attention? For example, the story behind the 2 APIs: https://rest.pay.nl/v1/ and https://rest-api.pay.nl/v16/. What is the idea behind it and what are your plans for it?

**Comment by escruickshank** [comment]
Hi! No problem at all. I will respond to the other questions via mail, as this is not the appropriate platform to discuss strategic decisions. Thank you again for your input, I will close this issue now.
