### ISSUE TITLE
orderId missing when returning on returnUrl

### ISSUE THREAD

**Issue by fgd007** [paynl/sdk#161]
I'm testing the API with this SDK (in testmode) and I noticed that when I come back to the returnUrl after completing the transaction no orderId nor other parameters are appended. Looking at my code (months old code that I haven't touched in a while) and at the README.md it should append an `orderId` right?

Am I missing something here?

**Comment by escruickshank** [comment]
Hi @fgd007, could you please send an email to my colleagues at support@pay.nl with your Merchant ID, transaction ID and other relevant info. We will be more than happy to have a look at this for you!

**Comment by fgd007** [comment]
I turns out to my own mistake. It was a internal redirection (without preserving query parameters). Classic mistake

**Comment by escruickshank** [comment]
Happy to hear you found the problem! We all live and learn ;) 
Good luck with the implementation!
