### ISSUE TITLE
Unable to get orignal order amount from transaction/status

### ISSUE THREAD

**Issue by BackEndTea** [paynl/sdk#162]
All functions to retrieve the paid amount look like this, where the value is divided by 100 before being passed.

Working with floats when dealing with money usually isn't a very good choice. Instead we prefer to use `Money` objects from either [moneyPHP](https://github.com/moneyphp/money/) or [brick money](https://github.com/brick/money).
These however expect the full amount as an integer (with decimals as part of the number), or a decimal string.

Could you make the value parts of the API calls available through the SDK as well, instead of us having to rely on getting the underlying data array and  retrieve the data from there ourselves.

```php
    /**
     * @return float|int The original amount
     */
    public function getAmountOriginal()
    {
        return $this->data['paymentDetails']['amountOriginal']['value'] / 100;
    }

**Comment by woutse** [comment]
Thanks for your message. Could you please send your request to support@pay.nl? Then we'll take it from there!
