### ISSUE TITLE
Add config setting for time out

### ISSUE THREAD

**Issue by cappadaan** [paynl/sdk#164]
Feature request for config option to set the curl timeout:

example:

\Paynl\Config::setTimeOut('5');

Timeout in seconds.

**Comment by escruickshank** [comment]
Hi @cappadaan, thank you for your input! I will discuss this with our developers shortly and let you know if we are going to implement this.

**Comment by escruickshank** [comment]
Hi @cappadaan, could you maybe add a bit more information as to why you would like to see this change? Is the default timeout too long maybe? Or would you like to be able to cut off the request earlier?

**Comment by BackEndTea** [comment]
Just any FYI, we added this snippet to set a 10 second timeout

```php
$curl = Config::getCurl();
        if (method_exists($curl, 'setTimeout')) {
            $curl->setTimeout(10);
        }
```
