### ISSUE TITLE
SDK still uses legacy endpoints?

### ISSUE THREAD

**Issue by robiningelbrecht** [paynl/sdk#165]
We've been using this SDK for a few years now and everything seems to be working fine. However, I was reading the PayNL docs, and noticed that the SDK uses legacy endpoints only. Is there a reason for doing so?

<img width="1033" alt="image" src="https://github.com/paynl/sdk/assets/203894/7a8585ef-2ee0-4cb2-8d66-037eb2f9b79a">

**Comment by escruickshank** [comment]
Hi @robiningelbrecht, thank you for your message. At the moment we only offer the API's directly for custom integrations. The new SDK, which uses the fully restful endpoints, is under development. As soon as this is released, I can let you know. Or if you would like to be included in the testing phase don't hesitate to drop me an e-mail at ellen@pay.nl
