### ISSUE TITLE
How to use the payment authorize api

### ISSUE THREAD

**Issue by iReserveApps** [paynl/sdk#169]
Usecase: we want to accept card payments and have collected the card data during checkout phase. 
Once we use the Transaction::start  with method 706 (or any card method), the payment url is redirecting to Visa/MC and user has to re-enter card details. 

In API documentation it says to use the payment authorize. 
This API is present in the SDK, so we experimented calling this one. 

public static function authorize(
        Model\Authorize\Transaction $transaction,
        Model\Payment $payment
    )

Required the two models. 
Payment is straightforward -> uses the card model. 
The transaction is not clear: requesting an orderId and an entranceCode

What is the proper usage here?

**Comment by woutse** [comment]
Thank you for your message, but can you please direct your question to support@pay.nl? Thanks in advance.
