### ISSUE TITLE
Deprecated Functionality messages in Magento log

### ISSUE THREAD

**Issue by fmm-rwalraven** [paynl/sdk#171]
PAY.DEBUG: Transactie start mislukt: Deprecated Functionality: trim(): Passing null to parameter #1 ($string) of type string is deprecated in vendor/paynl/sdk/src/Helper.php on line 165 | 0 [] []

https://github.com/paynl/sdk/blob/968b6f148d41b90a13e885226e6f9e6809d7d231/src/Helper.php#L165

Please change this line to
```php
$strAddress = trim($strAddress ?? "");
```

**Comment by woutse** [comment]
Thanks for your message! We'll make this change and submit it for the next release.

**Comment by woutse** [comment]
Thanks again for your message. Fixed in 2.2.2
