### ISSUE TITLE
Alternatieve spelling canceled

### ISSUE THREAD

**Issue by BondITSolutions** [paynl/sdk#2]
In `Paynl\Result\Transaction` is de functie `isCanceled` aanwezig, een alternatieve spelling is met twee l'en (cancelled). Is het misschien een idee om een alias aan te maken die `isCancelled` heet? Wij gebruiken intern namelijk toevallig 'Cancelled' i.p.v. 'Canceled' waardoor je bijv. situaties krijgt als:

    $transaction = \Paynl\Transaction::getForExchange();
    if($transaction->isCanceled()) {
        $payment->setStatus('Cancelled');
    }

**Comment by andypieters** [comment]
Ik zal er een alias voor maken.
Echter ga ik er geen nieuwe release voor maken.
Je mag ook een pull request indienen.

**Comment by andypieters** [comment]
De wijziging is doorgevoerd in de laatste release
