### ISSUE TITLE
getPaymentOptions en paymentProfileId

### ISSUE THREAD

**Issue by julianrutten** [paynl/sdk#25]
Is het mogelijk om de API methode ```getPaymentOptions``` (v2)  te implementeren? Wij gebruiken dit voor de betalen met credits methode in jullie systeem. met ```getPaymentOptions``` halen we de verschillende prijzen/credits op, en geven deze dan mee terug als ```amount```.

Edit: Zie dat ```getPaymentOptions``` niet werkt met serviceId, en de methode ```transaction\getServicePaymentOptions``` geeft ook niet de gewenste informatie, terwijl mij dat wel het gewenste gedrag lijkt.

**Comment by andypieters** [comment]
Helaas niet.
Het creditsysteem is een oud systeem dat we nog wel supporten met de oude api's maar niet meer actief door ons ontwikkeld wordt.
De api's die je nodig hebt werken ook niet zoals de nieuwe api's met APItoken en serviceId.
Maar voor deze API's moet je token, accountId, ProgramId, WebsiteId en WebsiteLocationId meegeven.
De SDK is bedoeld voor de meer simpele transacties.

**Comment by julianrutten** [comment]
Dat dacht ik al inderdaad, wat wel jammer is aangezien het wel een mooiere oplossing is als de betaalpakketen bij jullie worden bewaard in plaats van zowel bij jullie als bij ons.  Als alternatief heb ik de repo geforked en het alsnog in de SDK gezet. Issue mag inderdaad gesloten worden.

**Comment by andypieters** [comment]
De mooiste oplossing zou zijn dat je zelf bijhoudt wie hoeveel credits heeft.
De manier waarop ze credits krijgen kun je dan helemaal zelf bepalen.
Je zou ons platform dan alleen kunnen gebruiken voor het kopen van credits, je bepaald zelf het te betalen bedrag en de klant rekent het af.
Zodra de betaling gedaan is, krijg je een exchange bericht van ons dat de betaling gelukt is, en de credits kunnen worden bijgeschreven (in jouw systeem).
