### ISSUE TITLE
missing gender in invoiceAddress on enduser

### ISSUE THREAD

**Issue by fruitl00p** [paynl/sdk#26]
Seems that the 'gender' field on an invoice address is missing from being filled?

Also i'd like to recommend that the invoiceAddress be filled with $endUser fields before having specific endUser['invoiceAddress'] fields overwrite them...
That way one would only have to fill the different data (i.e. the actual address) but it would allow overwriting them with different and more specific values...

**Comment by andypieters** [comment]
Added in: https://github.com/paynl/sdk/pull/27

I will take filling the invoiceAddress with the address and enduser fields into consideration.

**Comment by fruitl00p** [comment]
thanks!
