### ISSUE TITLE
Fieldlengths ?

### ISSUE THREAD

**Issue by fruitl00p** [paynl/sdk#36]
A quick question as I cant seem to find any information about this (yet): Is there a specification of fieldlengths? (i.e. max length of a lastname, firstname or any other field) somewhere? The current request just takes all the information as is without performing any pre-flight checks on the data... 

Are there any plans to include some time of pre-flight validation?

**Comment by AubreyHewes** [comment]
@fruitl00p I ran test transactions changing the length of each field one by one ;-)... this gave me at least _some_ specification of the request payload from server-side validation exceptions;

The following are the consumer filled fields..

|path|server exception|note|
|-|-|-|
|.deliveryDate|PAY-405 - Parameter 'deliveryDate' is invalid: Invalid date format|_should be d-m-Y_|
|.enduser.gender|PAY-405 - Parameter 'gender' is invalid: Input is too long, maximum length is 1|
|.address.country, .invoiceAddress.country|PAY-405 - Parameter 'country' is invalid: Input is too long, maximum length is 2|
|.enduser.initials, .invoiceAddress.initials|PAY-405 - Parameter 'initials' is invalid: Input is too long, maximum length is 32|
|.enduser.lastName, .invoiceAddress.lastName|PAY-405 - Parameter 'lastName' is invalid: Input is too long, maximum length is 32|
|.address.streetName, .invoiceAddress.streetName|PAY-405 - Parameter 'streetName' is invalid: Input is too long, maximum length is 45|
|.address.houseNumber, .invoiceAddress.houseNumber|PAY-405 - Parameter 'streetNumber' is invalid: Input is too long, maximum length is 45|
|.address.city, .invoiceAddress.city|PAY-405 - Parameter 'city' is invalid: Input is too long, maximum length is 40|
|.address.zipCode, .invoiceAddress.zipCode|PAY-405 - Parameter 'zipCode' is invalid: Input is too long, maximum length is 24|
|.enduser.dob, .enduser.birthDate|PAY-405 - Parameter 'dob' is invalid: Input is too long, maximum length is 32|
|.enduser.emailAddress|PAY-405 - Parameter 'consumerEmail' is invalid: Input is too long, maximum length is 100|
|.company.name|PAY-405 - Parameter 'name' is invalid: Input is too long, maximum length is 128|
|.company.cocNumber|PAY-405 - Parameter 'cocNumber' is invalid: Input is too long, maximum length is 64|
|.company.vatNumber|PAY-405 - Parameter 'vatNumber' is invalid: Input is too long, maximum length is 32|

`.enduser.phoneNumber`, `.address.houseNumberExtension`, `.invoiceAddress.houseNumberExtension` do not seem to have a maximum length..

I don't know if this is enough to validate against or if there are other limits; i.e. line-breaks, diacritics, special characters, unicode etc.. ? It seems as long as you are within the length it will accept anything.

Also if sending `enduser.dob` then it does not _need_ to be a valid date; the following is valid "14-05-1999 123" ? Though in the examples and source `dob` has been replaced with `birthDate`.. which is parsed to a datetime (pre-flight like the other date fields) and then sent as `dob` ? Note with the dates if setting an empty string or incorrect format the pre-flight datetime conversion may output a different date than expected.

Also the `enduser.emailAddress` does not _need_ to be a valid email address; the following is valid "test pay.nl 123" ?
