### ISSUE TITLE
Testing transactions

### ISSUE THREAD

**Issue by fruitl00p** [paynl/sdk#37]
Currently the `transaction::start()`-method actually sends the transaction to you in order to return a TransactionID. Even including the testmode=1 into the transaction the callback is still fired (and e-mails errors in regards to not being able to hit the callback)

Is there anyway to prevent these unnecessary e-mails (or to simulate the callback in someway manually?)

**Comment by andypieters** [comment]
Testmode = 1 starts a real transaction, but in testmode.
All Callbacks and emails are sent, if you don't want it to send a callback, you can omit the exchangeUrl.

**Comment by fruitl00p** [comment]
Thanks! But that means that there is no way to simulate the callback manually?
