### ISSUE TITLE
Transaction expire time

### ISSUE THREAD

**Issue by LorenzV** [paynl/sdk#44]
In the Paynl API you can set a property "expire" which indicates how many seconds it takes for a transaction to expire. How do i do this with the SDK? I saw that you can set "expireDate". However, the Paynl API says nothing about a field named "expireDate".

**Comment by andypieters** [comment]
See: https://admin.pay.nl/docpanel/api/Transaction/start/7

It is the argument transaction.expireDate
By the way, it is not how many seconds the link is valid, but it is a datetime in CET

Be aware that this only works for paylinks (transactions without paymentmethod id)
