### ISSUE TITLE
Serious memory leak issue in php-curl-class < 8.1.0

### ISSUE THREAD

**Issue by LucHuygen** [paynl/sdk#52]
Just FYI: there is a serious memory leak issue in the php-curl-class before version 8.1.0 (fix was 2018-05-23)!

A reference to the class (including low-level curl handles) was kept in memory preventing release so you would run out of memory and/or connection handles if you keep PHP running as a daemon or something similar. 
This will cause all sorts of weird problems which are hard to track down.

**Comment by andypieters** [comment]
Iam sorry this took so long.
I updated the master right after your message, but after that forgot all about it.
I am now using php-curl-class 8.3, seems to work just fine.

But now i am running into a problem, maybe you can help me with that.
upgrading the sdk from 1.5.5 to 1.5.6 doesn't work.
Composer raises an error: - Can only install one of: php-curl-class/php-curl-class[4.10.0, 8.3.3].

Strange thing is, removing paynl/sdk and requiring 1.5.6 works. 

From an empty directory run:

```bash
composer require paynl/sdk:1.5.5 
composer require paynl/sdk:1.5.6
```
It won't install 1.5.6, but if you run
```bash
composer remove paynl/sdk
composer require paynl/sdk:1.5.6
```
It installs fine.

**Comment by andypieters** [comment]
Thanks!
Normally i use require to install a specific version, this usually works fine.
But indeed, update is meant for that.
Closing this issue
