### ISSUE TITLE
PAY-103 - Token not valid for this company

### ISSUE THREAD

**Issue by jasperf** [paynl/sdk#53]
Getting a `PAY-103 - Token not valid for this company` error. Any ideas how company is checked? `PAY_TOKEN` is set as is `SERVICE_ID` so not sure what to do here. And have not found this error message either..

**Comment by andypieters** [comment]
I suspect you are using a token from company1 end serviceid from company2.
If you really think this is an error, please send an email to support@pay.nl so we can assist you there.

**Comment by jasperf** [comment]
It appeared the account was closed due to inactivity. So I assume that was the issue. We are creating a new account now and will do a test again tomorrow. Will leave feedback again once I have more news.
