### ISSUE TITLE
Transaction parameters do not match SDK Docs

### ISSUE THREAD

**Issue by barryvdh** [paynl/sdk#61]
This package uses different parameters then described in https://docs.pay.nl/developers#transactions-start and https://docs.pay.nl/developers#instore-start 

Examples:

SDKDocs | PHP SDK
--|--
finishUrl|returnUrl
paymentOptionId|paymentOption
paymentOptionSubId|bank
amount in cents|amount in decimal value

This is very unclear and is not mentioned in either the docs or this package. But for an official SDK, it would be expected to follow the official SDK docs.

I understand from https://github.com/paynl/sdk/issues/1 that this is intentional, but imho that should either belong in a seperate package (like https://github.com/paynl/omnipay-paynl) or you should transparently allow the options. Eg. when settings returnUrl, you can internally set finishUrl.
This only doesn't work for the amount obviously, and changing it now would be a big BC break.

**Comment by andypieters** [comment]
Thanks for your feedback.

Actually docs.pay.nl is not the documentation for this SDK, but for our API.
I'll let my colleague remove (SDK) from the title, because the only thing that documetation mentions about the SDK is the location of it (this github repository)
