### ISSUE TITLE
Method Api\GetAllTerminals::setHash does not exists

### ISSUE THREAD

**Issue by ivodvb** [paynl/sdk#8]
Instore::getAllTerminals calls Api\GetAllTerminals::setHash if $options exists and has key hash.

- Var $options is not set
- Api\GetAllTerminals::setHash does not exists

**Comment by andypieters** [comment]
True, the getAllTerminals API doesn't take any arguments.
I think i copy pasted the function above it, but forgot to remove the statement.
I also noticed the method returns a Result\Instore\Status, i'll return a Result\Instore\Terminals here in the next update.
Thanks for reporting and for the pull requests :)

**Comment by andypieters** [comment]
Fixed
